const statesData = [
  {
    name: 'Andhra Pradesh',
    slug: 'andhra-pradesh',
    capital: 'Amaravati',
    description: 'Andhra Pradesh is a state on the southeastern coast of India known for its rich history, diverse culture, and the sacred Tirumala Venkateswara Temple. It boasts a long coastline along the Bay of Bengal and is famous for Kuchipudi dance, Venkateswara Temple at Tirupati, and Araku Valley hill station.',
    tourismTagline: 'The Kohinoor of India',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical with hot summers and moderate winters',
    averageTemperature: '26°C - 38°C',
    population: '5.4 Crores',
    area: '1,62,968 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Arunachal Pradesh',
    slug: 'arunachal-pradesh',
    capital: 'Itanagar',
    description: 'Arunachal Pradesh is the northeasternmost state, known for its breathtaking landscapes, snow-capped mountains, monasteries, and diverse tribal cultures. It is home to the Tawang Monastery and offers stunning views of the Eastern Himalayas.',
    tourismTagline: 'The Land of the Dawn-lit Mountains',
    bestTimeToVisit: 'September to May',
    climate: 'Alpine to subtropical',
    averageTemperature: '5°C - 30°C',
    population: '15 Lakhs',
    area: '83,743 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Assam',
    slug: 'assam',
    capital: 'Dispur',
    description: 'Assam is the gateway to the northeastern region, famous for its tea gardens, the Brahmaputra River, Kaziranga National Park, and the one-horned rhinoceros. It is known for its rich silk traditions and Bihu festival.',
    tourismTagline: 'The Land of Red Rivers and Blue Hills',
    bestTimeToVisit: 'October to April',
    climate: 'Tropical monsoon',
    averageTemperature: '15°C - 32°C',
    population: '3.5 Crores',
    area: '78,438 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Bihar',
    slug: 'bihar',
    capital: 'Patna',
    description: 'Bihar is a state rich in ancient history, home to Buddhist and Jain pilgrimage sites like Bodh Gaya, Nalanda, and Rajgir. It was the center of the Maurya and Gupta empires.',
    tourismTagline: 'The Land of Buddha and Gandhi',
    bestTimeToVisit: 'October to March',
    climate: 'Subtropical',
    averageTemperature: '10°C - 38°C',
    population: '12.4 Crores',
    area: '94,163 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Chhattisgarh',
    slug: 'chhattisgarh',
    capital: 'Raipur',
    description: 'Chhattisgarh is known for its rich tribal culture, dense forests, waterfalls, and ancient temples. It is home to the famous Chitrakote Falls and the Barnawapara Wildlife Sanctuary.',
    tourismTagline: 'The Heart of India',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical',
    averageTemperature: '15°C - 35°C',
    population: '3.0 Crores',
    area: '1,35,192 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Goa',
    slug: 'goa',
    capital: 'Panaji',
    description: 'Goa is Indias smallest state but a global tourist destination, famous for its pristine beaches, Portuguese colonial architecture, vibrant nightlife, and delicious seafood. It is known as the party capital of India.',
    tourismTagline: 'The Pearl of the Orient',
    bestTimeToVisit: 'November to February',
    climate: 'Tropical monsoon',
    averageTemperature: '20°C - 32°C',
    population: '15 Lakhs',
    area: '3,702 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Gujarat',
    slug: 'gujarat',
    capital: 'Gandhinagar',
    description: 'Gujarat is a vibrant western Indian state known for its rich cultural heritage, the Statue of Unity, the Rann of Kutch, Gir National Park (home to Asiatic lions), and the Sabarmati Ashram.',
    tourismTagline: 'The Jewel of Western India',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical arid to semi-arid',
    averageTemperature: '15°C - 40°C',
    population: '6.4 Crores',
    area: '1,96,024 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Haryana',
    slug: 'haryana',
    capital: 'Chandigarh',
    description: 'Haryana is a state with a rich historical and cultural heritage, known for its Vedic traditions, the city of Kurukshetra, and as a major agricultural hub contributing significantly to Indias food production.',
    tourismTagline: 'The Land of Warriors',
    bestTimeToVisit: 'October to March',
    climate: 'Continental',
    averageTemperature: '5°C - 42°C',
    population: '2.9 Crores',
    area: '44,212 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Himachal Pradesh',
    slug: 'himachal-pradesh',
    capital: 'Shimla',
    description: 'Himachal Pradesh is a paradise for nature lovers, known for its majestic Himalayan landscapes, hill stations, adventure sports, and Buddhist monasteries. It is often called Dev Bhoomi or the Land of Gods.',
    tourismTagline: 'The Land of Gods',
    bestTimeToVisit: 'March to June and September to November',
    climate: 'Alpine to subtropical',
    averageTemperature: '0°C - 30°C',
    population: '75 Lakhs',
    area: '55,673 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Jharkhand',
    slug: 'jharkhand',
    capital: 'Ranchi',
    description: 'Jharkhand is known for its dense forests, waterfalls, and rich mineral resources. It is home to the Betla National Park, Hundru Falls, and the ancient Sun Temple at Deoghar.',
    tourismTagline: 'The Land of Forests and Waterfalls',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical',
    averageTemperature: '10°C - 36°C',
    population: '3.7 Crores',
    area: '79,714 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Karnataka',
    slug: 'karnataka',
    capital: 'Bengaluru',
    description: 'Karnataka is a state of contrasts, from the tech hub of Bengaluru to the ancient ruins of Hampi, lush coffee plantations of Coorg, and pristine beaches of Gokarna. It offers a blend of heritage, nature, and modernity.',
    tourismTagline: 'One State, Many Worlds',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical to temperate',
    averageTemperature: '15°C - 35°C',
    population: '6.8 Crores',
    area: '1,91,791 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Kerala',
    slug: 'kerala',
    capital: 'Thiruvananthapuram',
    description: 'Kerala is known as Gods Own Country, renowned for its serene backwaters, lush hill stations, pristine beaches, Ayurvedic treatments, and rich cultural heritage. It is one of Indias most popular tourist destinations.',
    tourismTagline: 'Gods Own Country',
    bestTimeToVisit: 'September to March',
    climate: 'Tropical monsoon',
    averageTemperature: '20°C - 32°C',
    population: '3.5 Crores',
    area: '38,863 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Madhya Pradesh',
    slug: 'madhya-pradesh',
    capital: 'Bhopal',
    description: 'Madhya Pradesh is the heart of India, known for its ancient temples of Khajuraho, the Sanchi Stupa, wildlife sanctuaries like Kanha and Bandhavgarh, and the historic city of Gwalior.',
    tourismTagline: 'The Heart of Incredible India',
    bestTimeToVisit: 'October to March',
    climate: 'Subtropical',
    averageTemperature: '10°C - 40°C',
    population: '8.5 Crores',
    area: '3,08,252 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Maharashtra',
    slug: 'maharashtra',
    capital: 'Mumbai',
    description: 'Maharashtra is a diverse state ranging from the bustling metropolis of Mumbai to the ancient Ajanta and Ellora caves, hill stations like Lonavala, and the pristine beaches of Konkan.',
    tourismTagline: 'Maharashtra Unlimited',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical to coastal',
    averageTemperature: '12°C - 38°C',
    population: '12.4 Crores',
    area: '3,07,713 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Manipur',
    slug: 'manipur',
    capital: 'Imphal',
    description: 'Manipur is a northeastern state known for its natural beauty, classical Ras Leela dance, the floating Loktak Lake, and the Keibul Lamjao National Park.',
    tourismTagline: 'The Jewel of India',
    bestTimeToVisit: 'October to March',
    climate: 'Temperate',
    averageTemperature: '5°C - 30°C',
    population: '30 Lakhs',
    area: '22,327 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Meghalaya',
    slug: 'meghalaya',
    capital: 'Shillong',
    description: 'Meghalaya is known as the abode of clouds, famous for its living root bridges, the wettest place on earth Mawsynram, crystal-clear rivers, and the scenic hills of Shillong.',
    tourismTagline: 'The Abode of Clouds',
    bestTimeToVisit: 'October to June',
    climate: 'Subtropical highland',
    averageTemperature: '4°C - 28°C',
    population: '35 Lakhs',
    area: '22,429 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Mizoram',
    slug: 'mizoram',
    capital: 'Aizawl',
    description: 'Mizoram is a beautiful state in Northeast India known for its rolling hills, vibrant tribal culture, the Champhai wine region, and lush bamboo forests.',
    tourismTagline: 'The Land of the Blue Mountains',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical to temperate',
    averageTemperature: '10°C - 30°C',
    population: '12 Lakhs',
    area: '21,081 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Nagaland',
    slug: 'nagaland',
    capital: 'Kohima',
    description: 'Nagaland is known for its rich tribal heritage, the famous Hornbill Festival, scenic mountain ranges, and traditional Naga culture. It offers a unique cultural experience.',
    tourismTagline: 'The Land of Festivals',
    bestTimeToVisit: 'October to May',
    climate: 'Temperate',
    averageTemperature: '5°C - 30°C',
    population: '22 Lakhs',
    area: '16,579 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Odisha',
    slug: 'odisha',
    capital: 'Bhubaneswar',
    description: 'Odisha is a state known for its ancient temples, classical Odissi dance, the Sun Temple at Konark, Puri Jagannath Temple, Chilika Lake, and pristine beaches.',
    tourismTagline: 'The Soul of Incredible India',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical',
    averageTemperature: '12°C - 38°C',
    population: '4.6 Crores',
    area: '1,55,707 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Punjab',
    slug: 'punjab',
    capital: 'Chandigarh',
    description: 'Punjab is a vibrant state known for its rich Sikh heritage, the Golden Temple in Amritsar, Bhangra dance, delicious cuisine, and the spirit of hospitality.',
    tourismTagline: 'The Land of Five Rivers',
    bestTimeToVisit: 'October to March',
    climate: 'Continental',
    averageTemperature: '2°C - 42°C',
    population: '3.0 Crores',
    area: '50,362 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Rajasthan',
    slug: 'rajasthan',
    capital: 'Jaipur',
    description: 'Rajasthan is the largest state by area, known for its desert landscapes, majestic forts and palaces, vibrant culture, camel safaris, and the colorful cities of Jaipur, Jodhpur, and Udaipur.',
    tourismTagline: 'The Land of Kings',
    bestTimeToVisit: 'October to March',
    climate: 'Arid to semi-arid',
    averageTemperature: '5°C - 45°C',
    population: '7.8 Crores',
    area: '3,42,239 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Sikkim',
    slug: 'sikkim',
    capital: 'Gangtok',
    description: 'Sikkim is a Himalayan state known for its breathtaking landscapes, Mount Kanchenjunga views, Buddhist monasteries, and pristine natural beauty. It is Indias first organic state.',
    tourismTagline: 'The Paradise on Earth',
    bestTimeToVisit: 'March to June and September to November',
    climate: 'Alpine to subtropical',
    averageTemperature: '-5°C - 25°C',
    population: '6.5 Lakhs',
    area: '7,096 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Tamil Nadu',
    slug: 'tamil-nadu',
    capital: 'Chennai',
    description: 'Tamil Nadu is a state steeped in ancient Dravidian culture, known for its magnificent temple architecture, classical Bharatanatyam dance, hill stations like Ooty, and the pristine beaches of the Coromandel Coast.',
    tourismTagline: 'The Land of Temples',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical',
    averageTemperature: '18°C - 38°C',
    population: '7.7 Crores',
    area: '1,30,058 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Telangana',
    slug: 'telangana',
    capital: 'Hyderabad',
    description: 'Telangana is a state with a rich history, from the Charminar and Golconda Fort to the modern IT hub of Hyderabad. It is known for its unique cuisine, pearl trade, and cultural heritage.',
    tourismTagline: 'The Land of the Ganga-Jamuni Tehzeeb',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical semi-arid',
    averageTemperature: '15°C - 40°C',
    population: '3.9 Crores',
    area: '1,12,077 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Tripura',
    slug: 'tripura',
    capital: 'Agartala',
    description: 'Tripura is a northeastern state known for its royal palaces, ancient temples, and lush green landscapes. It is famous for the Ujjayanta Palace, Tripureswari Temple, and rich tribal culture.',
    tourismTagline: 'The Land of Diversity',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical monsoon',
    averageTemperature: '10°C - 32°C',
    population: '40 Lakhs',
    area: '10,486 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Uttar Pradesh',
    slug: 'uttar-pradesh',
    capital: 'Lucknow',
    description: 'Uttar Pradesh is Indias most populous state, home to the iconic Taj Mahal in Agra, the sacred city of Varanasi on the Ganges, and a rich tapestry of Mughal and Indian history.',
    tourismTagline: 'The Heartland of India',
    bestTimeToVisit: 'October to March',
    climate: 'Subtropical',
    averageTemperature: '5°C - 42°C',
    population: '23.7 Crores',
    area: '2,40,928 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Uttarakhand',
    slug: 'uttarakhand',
    capital: 'Dehradun',
    description: 'Uttarakhand is known as Dev Bhoomi, famous for its Himalayan landscapes, Char Dham pilgrimage sites, adventure sports in Rishikesh, and the serene hill stations of Nainital and Mussoorie.',
    tourismTagline: 'The Land of the Gods',
    bestTimeToVisit: 'March to June and September to November',
    climate: 'Alpine to subtropical',
    averageTemperature: '-5°C - 35°C',
    population: '1.1 Crores',
    area: '53,483 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'West Bengal',
    slug: 'west-bengal',
    capital: 'Kolkata',
    description: 'West Bengal is a state of diverse culture, from the bustling city of Kolkata to the Himalayan beauty of Darjeeling, the Sundarbans mangroves, and the historical sites of Murshidabad.',
    tourismTagline: 'The Land of Tagore and Mother Teresa',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical to alpine',
    averageTemperature: '5°C - 38°C',
    population: '9.8 Crores',
    area: '88,752 sq km',
    coverImage: '',
    featured: true,
  },
];

const utsData = [
  {
    name: 'Andaman and Nicobar Islands',
    slug: 'andaman-and-nicobar-islands',
    capital: 'Port Blair',
    description: 'The Andaman and Nicobar Islands are a tropical paradise known for their pristine white-sand beaches, crystal-clear waters, coral reefs, and rich history. Popular for water sports, island hopping, and the Cellular Jail.',
    tourismTagline: 'The Emerald Islands',
    bestTimeToVisit: 'October to May',
    climate: 'Tropical',
    averageTemperature: '22°C - 32°C',
    population: '4 Lakhs',
    area: '8,249 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Chandigarh',
    slug: 'chandigarh',
    capital: 'Chandigarh',
    description: 'Chandigarh is Indias first planned city, designed by the famous architect Le Corbusier. It is known for the Rock Garden, Sukhna Lake, Capitol Complex, and its high quality of life.',
    tourismTagline: 'The City Beautiful',
    bestTimeToVisit: 'September to March',
    climate: 'Subtropical',
    averageTemperature: '5°C - 38°C',
    population: '12 Lakhs',
    area: '114 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    slug: 'dadra-and-nagar-haveli-and-daman-and-diu',
    capital: 'Daman',
    description: 'This union territory offers a blend of Portuguese colonial heritage, serene beaches, and lush green landscapes. Daman and Diu are known for their forts, churches, and peaceful beaches.',
    tourismTagline: 'Silent Beaches and Colonial Charm',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical',
    averageTemperature: '18°C - 35°C',
    population: '5.8 Lakhs',
    area: '603 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Delhi',
    slug: 'delhi',
    capital: 'Delhi',
    description: 'Delhi, the national capital territory, is a vibrant blend of ancient history and modernity. It is home to the Red Fort, Qutub Minar, India Gate, Lotus Temple, and a rich Mughal heritage.',
    tourismTagline: 'The Heart of India',
    bestTimeToVisit: 'October to March',
    climate: 'Subtropical',
    averageTemperature: '5°C - 42°C',
    population: '2.1 Crores',
    area: '1,484 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Jammu and Kashmir',
    slug: 'jammu-and-kashmir',
    capital: 'Srinagar',
    description: 'Jammu and Kashmir is a region of breathtaking beauty, known as Paradise on Earth. It features the Dal Lake, Mughal Gardens, snow-capped mountains, and the Vaishno Devi shrine.',
    tourismTagline: 'Paradise on Earth',
    bestTimeToVisit: 'April to October',
    climate: 'Alpine to subtropical',
    averageTemperature: '-5°C - 35°C',
    population: '1.3 Crores',
    area: '42,241 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Ladakh',
    slug: 'ladakh',
    capital: 'Leh',
    description: 'Ladakh is a high-altitude desert known for its stark, breathtaking landscapes, ancient Buddhist monasteries, adventure trekking, and the worlds highest motorable passes like Khardung La.',
    tourismTagline: 'The Land of High Passes',
    bestTimeToVisit: 'May to September',
    climate: 'Cold desert',
    averageTemperature: '-15°C - 30°C',
    population: '3 Lakhs',
    area: '59,146 sq km',
    coverImage: '',
    featured: true,
  },
  {
    name: 'Lakshadweep',
    slug: 'lakshadweep',
    capital: 'Kavaratti',
    description: 'Lakshadweep is an archipelago of stunning coral islands in the Arabian Sea, known for its pristine beaches, crystal-clear lagoons, water sports, and marine biodiversity.',
    tourismTagline: 'The Land of Coral Islands',
    bestTimeToVisit: 'October to May',
    climate: 'Tropical',
    averageTemperature: '25°C - 35°C',
    population: '70,000',
    area: '32 sq km',
    coverImage: '',
    featured: false,
  },
  {
    name: 'Puducherry',
    slug: 'puducherry',
    capital: 'Puducherry',
    description: 'Puducherry, also known as Pondicherry, is a charming coastal town with a distinct French colonial heritage, known for its French Quarter, Sri Aurobindo Ashram, and serene beaches.',
    tourismTagline: 'The French Riviera of the East',
    bestTimeToVisit: 'October to March',
    climate: 'Tropical',
    averageTemperature: '20°C - 35°C',
    population: '15 Lakhs',
    area: '479 sq km',
    coverImage: '',
    featured: true,
  },
];

export const allStates = [...statesData, ...utsData];
